eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

name:
  value: keshri

spring:
  cloud:
    config:
      override-system-properties: false

management:
  zipkin:
    tracing:
      endpoint: http://192.168.1.8:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0