server:
  port: 8060

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.8:5432/payment
    username: keshri
    password: keshri
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: 192.168.1.8:9092
    producer:
      bootstrap-servers: 192.168.1.8:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.keshri.ecommerce.notification.PaymentNotificationRequest

application:
  config:
    product-url: http://localhost:8222/api/v1/products