spring:
  datasource:
    url: jdbc:postgresql://products-database.c5c8eyuoup24.us-east-1.rds.amazonaws.com:5432/product
    username: keshri
    password: keshrixlabs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8050