spring:
  datasource:
#    url: jdbc:postgresql://products-database.c5c8eyuoup24.us-east-1.rds.amazonaws.com:5432/product
    url: jdbc:postgresql://192.168.1.8:5432/product
    username: keshri
#    password: keshrixlabs
    password: keshri
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    out-of-order: true
    debug: true
server:
  port: 8050