server:
  port: 8040

spring:
  data:
    mongodb:
      username: keshri
      password: keshri
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        #        todo json.trusted.packages should be more precisely tuned 5:21:10
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.keshri.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.keshri.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: keshri
    password: keshri
    properties:
      mail:
        smtp:
          trust: "*"
        #          todo need to make it precise for security on trust 5:22:00
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
