spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
management:
  zipkin:
    tracing:
      endpoint: http://192.168.1.8:9411/api/v2/spans